### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by sebald** [bgoscinski/ng-rx-redux#3]
Hi,

my question is super unrelated to your Redux implementation (which is awesome BTW!), but I am currently learning Rx and was wondering what the following line does:

``` javascript
// file: createReducer.js
state$.add(processedState$.subscribe(state$))
```

Thanks in advance.

**Comment by bgoscinski** [comment]
Hi, I'm really surprised that my repo got someone's attention! Thanks for good word :) I'm also learning Rx (through practice) so just keep in mind that my code might not be first-class reactive and written 100% in "Rx-way". 

To answer your question: `processedState$.subscribe(state$)` returns instance of subscription. Subscriptions can be "merged" using `.add` method so that they are `unsubscribe`d together.

See https://github.com/ReactiveX/rxjs/blob/master/doc/subscription.md for documentation about Subscription class and https://github.com/ReactiveX/rxjs/blob/master/src/Subject.ts#L41-L43 for the method I use in this sample :)

**Comment by sebald** [comment]
Thanks :)
